import type { Language } from "./types";

export const queueCountMessages: Record<Language, Partial<Record<Intl.LDMLPluralRule, string>> & { other: string }> = {
  en: { one: "{count} video", other: "{count} videos" },
  pl: { one: "{count} film", few: "{count} filmy", many: "{count} filmów", other: "{count} filmu" },
  de: { one: "{count} Video", other: "{count} Videos" },
  fr: { one: "{count} vidéo", many: "{count} vidéos", other: "{count} vidéos" },
  es: { one: "{count} vídeo", many: "{count} vídeos", other: "{count} vídeos" },
  "pt-BR": { one: "{count} vídeo", many: "{count} vídeos", other: "{count} vídeos" },
  ru: { one: "{count} видео", few: "{count} видео", many: "{count} видео", other: "{count} видео" },
  ja: { other: "{count}本の動画" },
  hu: { one: "{count} videó", other: "{count} videó" },
};

const en = {
  playQueue: "Play queue", addToQueue: "Add to queue", removeFromQueue: "Remove from queue",
  queueEmpty: "Your queue is empty", queueEmptyHint: "Add videos from their details or hold Select on a video.",
  clearQueue: "Clear queue", moveEarlier: "Move earlier", moveLater: "Move later",
  nextVideo: "Next video", previousVideo: "Previous video", upNext: "Up next", nowPlaying: "Now playing",
  queueFull: "Queue is full (100 videos)", feedVideos: "Latest videos", previousSlide: "Previous featured video", nextSlide: "Next featured video",
  queueLoadError: "Could not load the next video.",
};
type Messages = { [K in keyof typeof en]: string };
export const queueMessages: Record<Language, Messages> = {
  en,
  pl: { playQueue: "Kolejka", addToQueue: "Dodaj do kolejki", removeFromQueue: "Usuń z kolejki", queueEmpty: "Kolejka jest pusta", queueEmptyHint: "Dodaj filmy w szczegółach lub przytrzymaj przycisk wyboru na filmie.", clearQueue: "Wyczyść kolejkę", moveEarlier: "Przenieś wcześniej", moveLater: "Przenieś później", nextVideo: "Następny film", previousVideo: "Poprzedni film", upNext: "Następny w kolejności", nowPlaying: "Teraz odtwarzane", queueFull: "Kolejka jest pełna (100 filmów)", feedVideos: "Najnowsze filmy", previousSlide: "Poprzedni wyróżniony film", nextSlide: "Następny wyróżniony film", queueLoadError: "Nie udało się wczytać następnego filmu." },
  de: { playQueue: "Warteschlange", addToQueue: "Zur Warteschlange hinzufügen", removeFromQueue: "Aus Warteschlange entfernen", queueEmpty: "Deine Warteschlange ist leer", queueEmptyHint: "Füge Videos in den Details hinzu oder halte die Auswahltaste auf einem Video gedrückt.", clearQueue: "Warteschlange leeren", moveEarlier: "Nach vorne verschieben", moveLater: "Nach hinten verschieben", nextVideo: "Nächstes Video", previousVideo: "Vorheriges Video", upNext: "Als Nächstes", nowPlaying: "Aktuelle Wiedergabe", queueFull: "Warteschlange ist voll (100 Videos)", feedVideos: "Neueste Videos", previousSlide: "Vorheriges hervorgehobenes Video", nextSlide: "Nächstes hervorgehobenes Video", queueLoadError: "Das nächste Video konnte nicht geladen werden." },
  fr: { playQueue: "File de lecture", addToQueue: "Ajouter à la file", removeFromQueue: "Retirer de la file", queueEmpty: "Votre file est vide", queueEmptyHint: "Ajoutez des vidéos depuis leurs détails ou maintenez le bouton de sélection sur une vidéo.", clearQueue: "Vider la file", moveEarlier: "Déplacer vers le début", moveLater: "Déplacer vers la fin", nextVideo: "Vidéo suivante", previousVideo: "Vidéo précédente", upNext: "À suivre", nowPlaying: "En cours de lecture", queueFull: "La file est pleine (100 vidéos)", feedVideos: "Dernières vidéos", previousSlide: "Vidéo à la une précédente", nextSlide: "Vidéo à la une suivante", queueLoadError: "Impossible de charger la vidéo suivante." },
  es: { playQueue: "Cola de reproducción", addToQueue: "Añadir a la cola", removeFromQueue: "Quitar de la cola", queueEmpty: "Tu cola está vacía", queueEmptyHint: "Añade vídeos desde sus detalles o mantén pulsado el botón de selección sobre un vídeo.", clearQueue: "Vaciar cola", moveEarlier: "Mover hacia el principio", moveLater: "Mover hacia el final", nextVideo: "Vídeo siguiente", previousVideo: "Vídeo anterior", upNext: "A continuación", nowPlaying: "En reproducción", queueFull: "La cola está llena (100 vídeos)", feedVideos: "Últimos vídeos", previousSlide: "Vídeo destacado anterior", nextSlide: "Vídeo destacado siguiente", queueLoadError: "No se pudo cargar el siguiente vídeo." },
  "pt-BR": { playQueue: "Fila de reprodução", addToQueue: "Adicionar à fila", removeFromQueue: "Remover da fila", queueEmpty: "Sua fila está vazia", queueEmptyHint: "Adicione vídeos pelos detalhes ou mantenha o botão de seleção pressionado sobre um vídeo.", clearQueue: "Limpar fila", moveEarlier: "Mover para antes", moveLater: "Mover para depois", nextVideo: "Próximo vídeo", previousVideo: "Vídeo anterior", upNext: "A seguir", nowPlaying: "Reproduzindo agora", queueFull: "A fila está cheia (100 vídeos)", feedVideos: "Vídeos mais recentes", previousSlide: "Vídeo em destaque anterior", nextSlide: "Próximo vídeo em destaque", queueLoadError: "Não foi possível carregar o próximo vídeo." },
  ru: { playQueue: "Очередь воспроизведения", addToQueue: "Добавить в очередь", removeFromQueue: "Удалить из очереди", queueEmpty: "Очередь пуста", queueEmptyHint: "Добавляйте видео на странице описания или удерживайте кнопку выбора на видео.", clearQueue: "Очистить очередь", moveEarlier: "Переместить раньше", moveLater: "Переместить позже", nextVideo: "Следующее видео", previousVideo: "Предыдущее видео", upNext: "Далее", nowPlaying: "Сейчас воспроизводится", queueFull: "Очередь заполнена (100 видео)", feedVideos: "Новые видео", previousSlide: "Предыдущее выделенное видео", nextSlide: "Следующее выделенное видео", queueLoadError: "Не удалось загрузить следующее видео." },
  ja: { playQueue: "再生キュー", addToQueue: "キューに追加", removeFromQueue: "キューから削除", queueEmpty: "キューは空です", queueEmptyHint: "動画の詳細から追加するか、動画を選んで選択ボタンを長押ししてください。", clearQueue: "キューを空にする", moveEarlier: "前に移動", moveLater: "後に移動", nextVideo: "次の動画", previousVideo: "前の動画", upNext: "次に再生", nowPlaying: "再生中", queueFull: "キューがいっぱいです（100本）", feedVideos: "新着動画", previousSlide: "前の注目動画", nextSlide: "次の注目動画", queueLoadError: "次の動画を読み込めませんでした。" },
  hu: { playQueue: "Lejátszási sor", addToQueue: "Hozzáadás a sorhoz", removeFromQueue: "Eltávolítás a sorból", queueEmpty: "A lejátszási sor üres", queueEmptyHint: "Adj hozzá videókat a részleteknél, vagy tartsd lenyomva a kiválasztógombot egy videón.", clearQueue: "Sor törlése", moveEarlier: "Előrébb helyezés", moveLater: "Hátrébb helyezés", nextVideo: "Következő videó", previousVideo: "Előző videó", upNext: "Következik", nowPlaying: "Most játszott", queueFull: "A sor megtelt (100 videó)", feedVideos: "Legújabb videók", previousSlide: "Előző kiemelt videó", nextSlide: "Következő kiemelt videó", queueLoadError: "Nem sikerült betölteni a következő videót." },
};
