import type { Language } from "./types";
const en = {
  searchStartTitle: "What would you like to watch?", searchStartHint: "Enter a title, topic or channel name above.", searchEmptyHint: "Try a shorter phrase or a different spelling.",
  searchTitle: "Search", searchHint: "Search videos and channels", searchLibrary: "In your library", searchYoutube: "On YouTube",
  searchChannels: "Channels", searchEmpty: "No results for this search.", searchError: "Search could not be completed. Try again.", searchLoading: "Searching…", searchClear: "Clear search",
};
export const searchMessages: Record<Language, typeof en> = {
  en,
  pl: { searchStartTitle: "Co dziś oglądamy?", searchStartHint: "Wpisz wyżej tytuł, temat lub nazwę kanału.", searchEmptyHint: "Spróbuj krótszej frazy lub innej pisowni.", searchTitle: "Szukaj", searchHint: "Szukaj filmów i kanałów", searchLibrary: "W Twojej bibliotece", searchYoutube: "W YouTube", searchChannels: "Kanały", searchEmpty: "Brak wyników dla tego wyszukiwania.", searchError: "Nie udało się wyszukać. Spróbuj ponownie.", searchLoading: "Wyszukiwanie…", searchClear: "Wyczyść wyszukiwanie" },
  de: { searchStartTitle: "Was möchtest du ansehen?", searchStartHint: "Gib oben einen Titel, ein Thema oder einen Kanalnamen ein.", searchEmptyHint: "Versuche einen kürzeren Suchbegriff oder eine andere Schreibweise.", searchTitle: "Suchen", searchHint: "Videos und Kanäle suchen", searchLibrary: "In deiner Bibliothek", searchYoutube: "Auf YouTube", searchChannels: "Kanäle", searchEmpty: "Keine Ergebnisse für diese Suche.", searchError: "Die Suche ist fehlgeschlagen. Versuche es erneut.", searchLoading: "Suche läuft…", searchClear: "Suche löschen" },
  fr: { searchStartTitle: "Que souhaitez-vous regarder ?", searchStartHint: "Saisissez un titre, un sujet ou un nom de chaîne ci-dessus.", searchEmptyHint: "Essayez une expression plus courte ou une autre orthographe.", searchTitle: "Rechercher", searchHint: "Rechercher des vidéos et des chaînes", searchLibrary: "Dans votre bibliothèque", searchYoutube: "Sur YouTube", searchChannels: "Chaînes", searchEmpty: "Aucun résultat pour cette recherche.", searchError: "La recherche a échoué. Réessayez.", searchLoading: "Recherche…", searchClear: "Effacer la recherche" },
  es: { searchStartTitle: "¿Qué te gustaría ver?", searchStartHint: "Escribe arriba un título, un tema o el nombre de un canal.", searchEmptyHint: "Prueba una frase más corta u otra forma de escribirla.", searchTitle: "Buscar", searchHint: "Buscar vídeos y canales", searchLibrary: "En tu biblioteca", searchYoutube: "En YouTube", searchChannels: "Canales", searchEmpty: "No hay resultados para esta búsqueda.", searchError: "No se pudo completar la búsqueda. Inténtalo de nuevo.", searchLoading: "Buscando…", searchClear: "Borrar búsqueda" },
  "pt-BR": { searchStartTitle: "O que você quer assistir?", searchStartHint: "Digite acima um título, assunto ou nome de canal.", searchEmptyHint: "Tente uma frase mais curta ou outra grafia.", searchTitle: "Buscar", searchHint: "Buscar vídeos e canais", searchLibrary: "Na sua biblioteca", searchYoutube: "No YouTube", searchChannels: "Canais", searchEmpty: "Nenhum resultado para esta busca.", searchError: "Não foi possível concluir a busca. Tente novamente.", searchLoading: "Buscando…", searchClear: "Limpar busca" },
  ru: { searchStartTitle: "Что посмотрим?", searchStartHint: "Введите выше название видео, тему или название канала.", searchEmptyHint: "Попробуйте более короткий запрос или другое написание.", searchTitle: "Поиск", searchHint: "Искать видео и каналы", searchLibrary: "В вашей библиотеке", searchYoutube: "На YouTube", searchChannels: "Каналы", searchEmpty: "По этому запросу ничего не найдено.", searchError: "Не удалось выполнить поиск. Попробуйте ещё раз.", searchLoading: "Поиск…", searchClear: "Очистить поиск" },
  ja: { searchStartTitle: "何を見ますか？", searchStartHint: "上にタイトル、トピック、チャンネル名を入力してください。", searchEmptyHint: "短い語句や別の表記で検索してみてください。", searchTitle: "検索", searchHint: "動画とチャンネルを検索", searchLibrary: "ライブラリ内", searchYoutube: "YouTube", searchChannels: "チャンネル", searchEmpty: "検索結果がありません。", searchError: "検索できませんでした。もう一度お試しください。", searchLoading: "検索中…", searchClear: "検索をクリア" },
  hu: { searchStartTitle: "Mit szeretnél nézni?", searchStartHint: "Írj be fent egy címet, témát vagy csatornanevet.", searchEmptyHint: "Próbálj rövidebb kifejezést vagy más írásmódot.", searchTitle: "Keresés", searchHint: "Videók és csatornák keresése", searchLibrary: "A könyvtáradban", searchYoutube: "A YouTube-on", searchChannels: "Csatornák", searchEmpty: "Nincs találat erre a keresésre.", searchError: "A keresés sikertelen. Próbáld újra.", searchLoading: "Keresés…", searchClear: "Keresés törlése" },
};
