import { Check, ClosedCaption, LoaderCircle } from "lucide-react";
import type { AvailableSubtitle } from "../api";
import { useI18n } from "../i18n";
import { Menu, MenuItem, MenuSeparator, ScrollArea, Switch } from "./ui";

interface SubtitleMenuBodyProps {
  available: AvailableSubtitle[];
  selectedLanguage: string | null;
  preferredLanguages: string[];
  loadingLanguage: string | null;
  errorLanguage: string | null;
  onSelect: (language: string) => void;
  onToggle: () => void;
}

/** The on/off switch and language list. Shared by the CC button and the gear menu. */
export function SubtitleMenuBody({
  available,
  selectedLanguage,
  preferredLanguages,
  loadingLanguage,
  errorLanguage,
  onSelect,
  onToggle,
}: SubtitleMenuBodyProps) {
  const { t } = useI18n();
  const availableByLanguage = new Map(available.map((subtitle) => [subtitle.lang, subtitle]));
  const preferred = [...new Set(preferredLanguages.filter(Boolean))]
    .map((language) => availableByLanguage.get(language))
    .filter((language): language is AvailableSubtitle => Boolean(language));
  const preferredSet = new Set(preferred.map((language) => language.lang));
  const remaining = available.filter((subtitle) => !preferredSet.has(subtitle.lang));

  const status = (language: string) => (
    <span className="lp-sub-option-status">
      {selectedLanguage === language && <Check size={14} />}
      {loadingLanguage === language && <LoaderCircle className="spin" size={13} />}
      {errorLanguage === language && <span className="lp-sub-error">{t("subtitlesUnavailable")}</span>}
    </span>
  );

  return (
    <>
      <div className="lp-sub-toggle">
        <span>{t("subtitles")}</span>
        <Switch checked={Boolean(selectedLanguage)} onCheckedChange={onToggle} />
      </div>
      <ScrollArea className="lp-sub-menu-list-wrap" viewportClassName="lp-sub-menu-list">
        <Menu>
          {preferred.map((language) => (
            <MenuItem
              key={language.lang}
              selected={selectedLanguage === language.lang}
              disabled={loadingLanguage != null}
              onClick={() => onSelect(language.lang)}
              suffix={status(language.lang)}
            >
              {language.auto ? `${language.label} (${t("subtitlesAutoGenerated")})` : language.label}
            </MenuItem>
          ))}
          {preferred.length > 0 && remaining.length > 0 && <MenuSeparator />}
          {remaining.map((language) => (
            <MenuItem
              key={language.lang}
              disabled={loadingLanguage != null}
              onClick={() => onSelect(language.lang)}
              suffix={status(language.lang)}
            >
              {language.auto ? `${language.label} (${t("subtitlesAutoGenerated")})` : language.label}
            </MenuItem>
          ))}
          {available.length === 0 && <MenuItem disabled>{t("subtitlesNoneAvailable")}</MenuItem>}
        </Menu>
      </ScrollArea>
    </>
  );
}

interface SubtitlePickerProps {
  videoId?: string;
  selectedLanguage: string | null;
  loadingLanguage: string | null;
  onToggle: () => void;
}

/** The CC button: only switches subtitles on or off. Language and style live in the gear menu. */
export default function SubtitlePicker({ videoId, selectedLanguage, loadingLanguage, onToggle }: SubtitlePickerProps) {
  const { t } = useI18n();
  if (!videoId) return null;
  return (
    <button
      className={`lp-btn lp-cc${selectedLanguage ? " active" : ""}`}
      aria-label={t("subtitles")}
      aria-pressed={Boolean(selectedLanguage)}
      onClick={onToggle}
    >
      {loadingLanguage ? <LoaderCircle className="spin" size={19} /> : <ClosedCaption size={22} />}
    </button>
  );
}
